FLOAT_ENABLED = False

FLOAT_TRACE_HEADER = "X-Trace-ID"


FLOAT_AUTO_ENABLE_IN_TESTS = True


FLOAT_MAX_EVENTS = 10000

FLOAT_TTL_SECONDS = 300


FLOAT_AUTO_PRINT_REPORT = False

FLOAT_EXPORT_ON_EXIT = False
FLOAT_EXPORT_PATH = "logs/floats.jsonl"


FLOAT_INCLUDE_PATTERNS = []

FLOAT_EXCLUDE_PATTERNS = []


FLOAT_SEND_TO_OPENTELEMETRY = False
FLOAT_SEND_TO_DATADOG = False
FLOAT_SEND_TO_PROMETHEUS = False

FLOAT_WEBHOOK_URL = None
